# Generated by Django 4.2.5 on 2023-10-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0005_guest_user_alter_guest_email_alter_guest_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='user',
        ),
        migrations.AddField(
            model_name='guest',
            name='gid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Guest Id'),
        ),
    ]
