# Generated by Django 4.2.5 on 2023-10-23 05:49

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0008_delete_guest_remove_customuser_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_guest',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_host',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'guest'), (2, 'host'), (3, 'admin')], default=1),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_guest', models.BooleanField(default=True)),
                ('is_host', models.BooleanField(default=False)),
                ('guest_first_name', models.CharField(max_length=30)),
                ('guest_last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('staydemoapp.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_guest', models.BooleanField(default=False)),
                ('is_host', models.BooleanField(default=True)),
                ('host_first_name', models.CharField(max_length=100)),
                ('host_last_name', models.CharField(max_length=100)),
                ('license_upload', models.FileField(upload_to='licenses/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('staydemoapp.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
