# Generated by Django 4.2.5 on 2023-10-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0012_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='images',
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ManyToManyField(related_name='properties', to='staydemoapp.propertyimage'),
        ),
    ]
