# Generated by Django 4.2.5 on 2023-10-27 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0013_remove_property_images_property_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='property',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyCategory',
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
