# Generated by Django 4.2.5 on 2023-11-01 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0016_property_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staydemoapp.host')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staydemoapp.property')),
            ],
        ),
    ]
