# Generated by Django 4.2.5 on 2023-11-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0017_propertyapproval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyApproval',
        ),
    ]
