# Generated by Django 4.2.5 on 2023-11-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0020_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
