# Generated by Django 4.2.5 on 2023-11-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0027_alter_property_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
