# Generated by Django 4.2.5 on 2023-11-08 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0029_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='upload_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
