# Generated by Django 4.2.5 on 2023-11-11 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0030_property_upload_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='host',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='staydemoapp.host'),
        ),
    ]
