# Generated by Django 4.2.5 on 2023-11-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0031_alter_property_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('guest_count', models.PositiveIntegerField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staydemoapp.guest')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staydemoapp.property')),
            ],
        ),
    ]
