# Generated by Django 4.2.5 on 2023-11-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0032_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
