# Generated by Django 4.2.5 on 2023-11-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0034_guestbookingavailability_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='checkin_date',
            new_name='check_in_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='checkout_date',
            new_name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_count',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='num_guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='GuestBookingAvailability',
        ),
    ]
