# Generated by Django 4.2.5 on 2023-11-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0039_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
    ]
