# Generated by Django 4.2.5 on 2024-02-06 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0041_guide_alter_customuser_role'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='guide',
            name='customuser_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='service_photos/')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staydemoapp.guide')),
            ],
        ),
    ]
