# Generated by Django 4.2.5 on 2024-02-06 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0042_guide_guideid_alter_guide_customuser_ptr_service'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='guide',
            name='customuser_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
