# Generated by Django 4.2.5 on 2024-02-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0043_remove_guide_guideid_alter_guide_customuser_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
