# Generated by Django 4.2.5 on 2024-02-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0044_guide_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
