# Generated by Django 4.2.5 on 2024-02-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0046_guide_gender_guide_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
