# Generated by Django 4.2.5 on 2024-02-09 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0048_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='location',
        ),
    ]
