# Generated by Django 4.2.5 on 2024-02-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0050_guide_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='location',
        ),
    ]
