# Generated by Django 4.2.5 on 2024-02-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0051_remove_guide_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
