# Generated by Django 4.2.5 on 2024-02-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0052_delete_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
