# Generated by Django 4.2.5 on 2024-02-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0053_guide_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
