# Generated by Django 4.2.5 on 2024-02-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0056_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='location',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='price_per_person',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_name',
            new_name='service_title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='best_timing',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='service',
            name='best_timing_to_visit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('adventurous', 'Adventurous'), ('picnic', 'Picnic'), ('cultural', 'Cultural'), ('music_concerts', 'Music/Concerts')], default='adventurous', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='service',
            name='features',
            field=models.TextField(),
        ),
    ]
