# Generated by Django 4.2.5 on 2024-02-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0057_rename_location_service_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='features',
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.ManyToManyField(to='staydemoapp.feature'),
        ),
    ]
