# Generated by Django 4.2.5 on 2024-02-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0058_feature_remove_service_features_service_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
