# Generated by Django 4.2.5 on 2024-02-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0068_remove_addservice_images_alter_addservice_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addservice',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
        migrations.DeleteModel(
            name='ServiceImage',
        ),
    ]
