# Generated by Django 4.2.5 on 2024-02-19 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0069_addservice_images_delete_serviceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='addservice',
            name='guide',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='staydemoapp.guide'),
        ),
    ]
