# Generated by Django 4.2.5 on 2024-02-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0071_addservice_latitude_addservice_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
