# Generated by Django 4.2.5 on 2024-02-20 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0072_guide_latitude_guide_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='longitude',
        ),
    ]
