# Generated by Django 4.2.5 on 2024-02-20 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0073_remove_guide_latitude_remove_guide_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addservice',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='addservice',
            name='longitude',
        ),
    ]
