# Generated by Django 4.2.5 on 2024-02-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0075_addservice_latitude_addservice_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addservice',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='addservice',
            name='longitude',
        ),
    ]
