# Generated by Django 4.2.5 on 2024-02-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0081_remove_addservice_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='addservice',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
        migrations.DeleteModel(
            name='ServiceImage',
        ),
    ]
