# Generated by Django 4.2.5 on 2024-02-28 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0083_servicetimeslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceTimeSlot',
        ),
    ]
