# Generated by Django 4.2.5 on 2024-02-28 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0085_visittime_addservice_visit_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addservice',
            name='visit_times',
        ),
        migrations.AddField(
            model_name='addservice',
            name='visit_times',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='staydemoapp.visittime'),
        ),
    ]
