# Generated by Django 4.2.5 on 2024-02-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0086_remove_addservice_visit_times_addservice_visit_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addservice',
            name='visit_times',
        ),
        migrations.AddField(
            model_name='addservice',
            name='visit_times',
            field=models.ManyToManyField(blank=True, related_name='services', to='staydemoapp.visittime'),
        ),
    ]
