# Generated by Django 4.2.5 on 2024-02-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0087_remove_addservice_visit_times_addservice_visit_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='addservice',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
    ]
