# Generated by Django 4.2.5 on 2024-02-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0089_bookservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookService',
        ),
    ]
