# Generated by Django 4.2.5 on 2024-03-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0092_servicebooking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='status',
        ),
    ]
