# Generated by Django 4.2.5 on 2024-03-04 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0094_servicepayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicePayment',
        ),
    ]
