# Generated by Django 4.2.5 on 2024-03-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0095_delete_servicepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
