# Generated by Django 4.2.5 on 2024-03-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0096_servicebooking_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='razorpay_order_id',
        ),
    ]
