# Generated by Django 4.2.5 on 2024-03-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0098_servicepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepayment',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('not_completed', 'Not Completed')], default='not_completed', max_length=20),
        ),
    ]
