# Generated by Django 4.2.5 on 2024-03-16 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staydemoapp', '0099_servicepayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepayment',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('not_completed', 'Not Completed')], default='completed', max_length=20),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('reviewcomment', models.TextField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staydemoapp.guest')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staydemoapp.addservice')),
            ],
        ),
    ]
